version: '2'

services:
    mysql:
        image: mysql:5.6
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: yiimine
            MYSQL_USER: yiimine
            MYSQL_PASSWORD: yiimine_pass
        ports:
            - "3307:3306"
    nginx:
        image: nginx:latest
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8080:80"
    php:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        volumes:
            - ./:/var/www/yiimine